function has() {
    type "$1" &>/dev/null
}

function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	IFS= read -r -d '' cwd < "$tmp"
	[ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
	rm -f -- "$tmp"
}

# Do not share history across zsh instances
setopt nosharehistory

# Environment Variables
export TERM=xterm-256color
export GPG_TTY=$(tty)

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.ohmyzsh"
ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh


if [ -z "$LANG" ]; then
    export LANG=en_US.UTF-8
fi

if [ -d "$HOME"/.local/bin ] ; then
    export PATH="$HOME"/.local/bin:$PATH
fi

if has vim; then
    export EDITOR='vim'
elif has nvim; then
    export EDITOR='nvim'
elif has vi; then
    export EDITOR='vi'
fi

# Allow local customizations in the ~/.zshrc_local file
if [ -r "$HOME"/.zshrc.local ]; then
    source "$HOME"/.zshrc.local
fi
